Creating class StudentDataHolder
computacao-ufcg/eureca-backend pull request #53
Opened 2021-02-26 19:20 UTC by natalia-sa

- Rewriting methods of the application facade to remove logic and placing them in the new class StudentDataHolder

2021-02-26 21:52 UTC, fubica requested changes

2021-02-26 21:52 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/holders/StudentDataHolder.java
> +package br.edu.ufcg.computacao.eureca.backend.core.holders;
Na reunião eu concordei com o nome (Holder), mas não estava 100% certo de que estava concordando :-) Vejo agora que o nome não é adequado. As classes *Holder implementam uma espécie de cache de informação. Lê a informação uma vez e guarda em memória. Tipicamente a informação é imutável. No caso do StudentData, esse dado vem de uma fonte externa e, em produção, não é imutável. Daí, essa classe não deveria ser um Holder. Talvez pudéssemos chamar de StudentDataFetcher e colocá-la no pacote br.edu.ufcg.computacao.eureca.backend.core.

2021-02-26 23:07 UTC, natalia-sa commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/holders/StudentDataHolder.java
> +package br.edu.ufcg.computacao.eureca.backend.core.holders;
Entendi, vou modificar.

2021-02-27 09:38 UTC, fubica approved these changes

2021-02-27 09:38 UTC, merged