computing real data for enrollments statistics
computacao-ufcg/eureca-backend pull request #79
Opened 2021-06-24 21:20 UTC by jonatas-lima

2021-06-25 12:42 UTC, ielepassos approved these changes

2021-06-25 18:52 UTC, natalia-sa approved these changes

2021-06-26 09:41 UTC, fubica requested changes

2021-06-26 09:41 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/ApplicationFacade.java
> +//        authenticateAndAuthorize(token, EurecaOperation.GET_ENROLLMENTS_STATISTICS);
Por que a autenticação e autorização estão comentadas? Aqui basta criar um novo tipo de operação no Enumeration EurecaOperation.

2021-06-26 09:41 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +        TermCount max = new TermCount(-1, null);
Inicia com zero, ao invés de -1, já zero é um valor válido e -1 não.

2021-06-26 09:41 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +        double avgEnrollmentsPerPeriod = (double) totalEnrollments / totalTerms;
Só fazer o cast não funciona. A divisão de int/int vai truncar o valor e depois transformar isso em um double. Por exemplo, 10/3 = 3.0 ao invés de 3.333333... Uma forma de resolver isso, que eu usei em outras partes do código é transformar o int em um double através da multiplicação por 1.0. Ex. (1.0 * totalEnrollments) / totalClasses.

2021-06-26 09:41 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +        TermCount min = new TermCount(Integer.MAX_VALUE, null);
Verifique outros pontos do código que tem lógica similar e que não usam TermCount e faça o refatoramento necessário.

2021-06-26 09:41 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +
Esse código ainda está incompleto, correto? O código a partir da linha 92 (mock) precisa ser substituído.

2021-06-26 09:41 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/dao/scsvfiles/ScsvFilesDataAccessFacade.java
> +
Acho que o mais apropriado seria criar em IndexHolders um novo index do jeito que você precisa (EnrollmentsPerTermPerSubject). Isso seria feito apenas uma vez e no mesmo código que cria o index EnrollmentsPerSubjectPerTermPerClass.

2021-06-26 09:41 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/dao/scsvfiles/ScsvFilesDataAccessFacade.java
> +        return this.getFilteredEnrollments(from, to, courseCode, curriculumCode, enrollments);
Os indexes existem para não precisar pegar todos os enrollments e filtrar a cada chamada de uma função. Ou seja, o index já é o filtro que você precisa usar. Veja comentário acima.

2021-06-26 11:18 UTC, jonatas-lima commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/ApplicationFacade.java
> +//        authenticateAndAuthorize(token, EurecaOperation.GET_ENROLLMENTS_STATISTICS);
Era só para testar, pra não ter que pegar o token do AS

2021-06-26 11:20 UTC, jonatas-lima commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +        TermCount max = new TermCount(-1, null);
É o intuito, pois quando ele passar pelo primeiro número de matrículas ele já será considerado como menor. Se eu começar com 0, tem a possibilidade de todos os períodos possuírem 0 matrículas, e o term continuaria null.

2021-06-26 11:21 UTC, jonatas-lima commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +        double avgEnrollmentsPerPeriod = (double) totalEnrollments / totalTerms;
Acontece isso quando se faz primeiro a divisão e depois o casting: (double) (totalEnrollments / totalClasses). Assim é computado normalmente, porque ele faz o casting de totalEnrollments antes de dividir por totalClasses.

2021-06-26 11:22 UTC, jonatas-lima commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +
Sim, ainda falta concluir.

2021-06-26 11:28 UTC, jonatas-lima commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/dao/scsvfiles/ScsvFilesDataAccessFacade.java
> +
Acho que é necessário ser passado o curso e o currículo para fazer isso. No caso, utilizaria o EnvironmentVariablesHolder dentro da função, sem passar pelos parâmetros?

2021-06-26 15:36 UTC, jonatas-lima commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +        TermCount min = new TermCount(Integer.MAX_VALUE, null);
Essa é a primeira vez que é utilizado o TermCount no código, em outros pontos é utlizado o MetricsSummary.

2021-06-26 20:16 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +        TermCount max = new TermCount(-1, null);
Entendi. Então acho que precisa corrigir isso em outros pontos do código que têm uma lógica similar. Eu estava iniciando o máximo com zero.

2021-06-26 20:21 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/dao/scsvfiles/ScsvFilesDataAccessFacade.java
> +
Não deveria. Atualmente é criado o index EnrollmentsPerCurriculumPerSubjectPerTermPerClass. O que precisa ser criado é outro índice que organiza a informação de outra forma: EnrollmentsPerCurriculumPerTermPerSubject.

2021-06-26 20:28 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/eureca/backend/core/controllers/EnrollmentsStatisticsController.java
> +        TermCount min = new TermCount(Integer.MAX_VALUE, null);
ok.

2021-06-28 12:41 UTC, jonatas-lima reviewed
Foi mudado o tipo de resposta do endpoint /enrollments/summary/csv pois estava retornando vários glossários (um para cada objeto), agora retorna a coleção de resposta e apenas um glossário

2021-07-04 20:59 UTC, merged